version: 2

models:
  - name: stg_addresses
    description: address metadata
    columns:
      - name: address_id
        tests:
          - not_null
          - unique
      - name: address
        tests:
          - not_null
      - name: zipcode
        tests:
          - not_null
      - name: state
        tests:
          - not_null
      - name: country
        tests:
          - not_null
  - name: stg_events
    description: events on the platform with session and user
    columns:
      - name: event_id
        tests:
          - not_null
          - unique
      - name: user_id
        tests:
          - not_null
      - name: event_type
        tests:
          - not_null
      - name: created_at
        tests:
          - not_null
  - name: stg_order_items
    description: details about items in each order
    columns:
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: quantity
        tests:
          - positive_values
  - name: stg_orders
    description: order information including shipping and cost
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: user_id
        tests:
          - not_null
      - name: address_id
        tests:
          - not_null
  - name: stg_products
    description: product information including price and inventory details
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
      - name: name
        tests:
          - not_null
      - name: price
        tests:
          - positive_values
      - name: inventory
        tests: 
          - not_null
  - name: stg_promos
    description: promo details including discount and status
    columns:
      - name: promo_id
        tests:
          - not_null
          - unique
      - name: discount
        tests:
          - positive_values
      - name: status
        tests: 
          - not_null
  - name: stg_users
    description: user details including name and contact info
    columns:
      - name: user_id
        tests:
          - not_null
          - unique
      - name: address_id 
        tests:
          - not_null 