version: 2

models:

  - name: int_user_session
    description: todo
    columns:
      - name: user_id
        tests:
          - not_null
      - name: session_id
        tests:
          - not_null
          - unique

  - name: fact_page
    description: page stats
    columns:
      - name: page_url
        tests: 
          - not_null
  
  - name: fact_user_session
    description: user session lengths
    columns:
      - name: user_id
        tests:
          - not_null
      - name: session_id
        tests:
          - not_null
          - unique
      - name: session_length
        tests:
          - not_null
